name: Build, Push and Sign Kubernetes the hard way binaries image

on:
  push:
    branches:
      - main
    paths:
      - 'hack/rootfs/binaries/**'
  pull_request:
    branches:
      - main
    paths:
      - 'hack/rootfs/binaries/**'

permissions:
  contents: read
  packages: write        # grant write to registry (GHCR/Docker Hub)
  id-token: write       # needed for GitHub OIDC (keyless signing)

jobs:
  build-and-sign:
    name: Build and Sign Image
    runs-on: ubuntu-latest
    env:
      TARGET_OS: linux
      TARGET_ARCH: amd64
      K8S_VERSION: v1.34.0
      CRICTL_VERSION: v1.34.0
      RUNC_VERSION: v1.3.1
      CNI_PLUGINS: v1.7.1
      CONTAINERD_VERSION: "2.1.4"
      ETCD_VERSION: v3.6.4
      NERDCTL_VERSION: "2.1.4"
      HELM_VERSION: v3.18.6
      K9S_VERSION: v0.32.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Build Date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: hack/rootfs/binaries
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-binaries:${{ github.sha }}
          platforms: "linux/amd64"
          build-args: |
            K8S_VERSION=${{ env.K8S_VERSION }}
            CRICTL_VERSION=${{ env.CRICTL_VERSION }}
            RUNC_VERSION=${{ env.RUNC_VERSION }}
            CNI_PLUGINS=${{ env.CNI_PLUGINS }}
            CONTAINERD_VERSION=${{ env.CONTAINERD_VERSION }}
            ETCD_VERSION=${{ env.ETCD_VERSION }}
            NERDCTL_VERSION=${{ env.NERDCTL_VERSION }}
            HELM_VERSION=${{ env.HELM_VERSION }}
            K9S_VERSION=${{ env.K9S_VERSION }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.2

      - name: Sign image with Cosign
        run: |
          cosign sign --keyless ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-binaries:${{ github.sha }}

  verify-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-sign
    steps:
      - uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.2

      - name: Verify image signature
        run: |
          cosign verify ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-binaries:${{ github.sha }}